#!/usr/bin/env python3
"""
cv.json  ─┬─→  index.html   (website)
          └─→  cv.tex       (LaTeX → cv.pdf)

Usage:
    python3 build.py            # 두 파일 모두 생성
    python3 build.py --pdf      # 생성 후 pdflatex 까지 실행 (로컬에 TeX 필요)

표준 라이브러리만 사용합니다. 설치할 것 없습니다.
"""

import base64
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
BANNER_HTML = "<!-- GENERATED BY build.py FROM cv.json — DO NOT EDIT THIS FILE DIRECTLY. -->\n"
BANNER_TEX = "% GENERATED BY build.py FROM cv.json — DO NOT EDIT THIS FILE DIRECTLY.\n"

STATUS = {
    "published":      {"label": "Published",     "cls": "st pub", "tex": ""},
    "accepted":       {"label": "Accepted",      "cls": "st acc", "tex": "Accepted"},
    "in_revision":    {"label": "In revision",   "cls": "st",     "tex": "In revision"},
    "in_submission":  {"label": "In submission", "cls": "st",     "tex": "In submission"},
    "in_preparation": {"label": "In preparation","cls": "st",     "tex": "In preparation"},
}

ICONS = {
    "scholar":  '<path d="M12 2 1 8l11 6 9-4.9V17h2V8L12 2z"/><path d="M5 12.4V16c0 2.2 3.1 4 7 4s7-1.8 7-4v-3.6l-7 3.8-7-3.8z"/>',
    "orcid":    '<path d="M12 0a12 12 0 100 24 12 12 0 000-24zM7.1 6.3a1.1 1.1 0 110 2.2 1.1 1.1 0 010-2.2zM6.4 9.6h1.5v8.3H6.4V9.6zm3.5 0h3.3c3.2 0 4.6 2.3 4.6 4.2 0 2-1.6 4.1-4.6 4.1H9.9V9.6zm1.5 1.4v5.5h1.6c2.3 0 3.2-1.4 3.2-2.7 0-1.4-1-2.8-3.2-2.8h-1.6z"/>',
    "linkedin": '<path d="M4.98 3.5a2.5 2.5 0 11-.01 5.01A2.5 2.5 0 014.98 3.5zM3 9h4v12H3V9zm7 0h3.8v1.7h.05c.53-.95 1.83-1.95 3.76-1.95C21.6 8.75 23 11 23 14.4V21h-4v-5.9c0-1.4-.03-3.2-2-3.2-2 0-2.3 1.5-2.3 3.1V21h-4V9z"/>',
    "link":     '<path d="M10 13a5 5 0 007.5.5l3-3a5 5 0 00-7-7l-1.7 1.7M14 11a5 5 0 00-7.5-.5l-3 3a5 5 0 007 7l1.7-1.7" fill="none" stroke="currentColor" stroke-width="2"/>',
}


# ── inline markup ────────────────────────────────────────────────────────────
# {me}  → own name        †  → dagger
# _x_   → emphasis        [text](url) → link
TOKEN = re.compile(r"\{me\}|†|\[([^\]]+)\]\(([^)]+)\)|(?<!\w)_([^_]+)_(?!\w)")


def esc_html(t):
    return t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def esc_tex(t):
    out = []
    for ch in t:
        if ch in "&%$#_{}":
            out.append("\\" + ch)
        elif ch == "~":
            out.append("\\textasciitilde{}")
        elif ch == "^":
            out.append("\\textasciicircum{}")
        elif ch == "\\":
            out.append("\\textbackslash{}")
        else:
            out.append(ch)
    return "".join(out)


def esc_tex_url(u):
    for ch in "%#&":
        u = u.replace(ch, "\\" + ch)
    return u


def inline(text, mode, me="Taehyun Nam"):
    """Render the mini-markup for 'html' or 'tex'."""
    if text is None:
        return ""
    out, pos = [], 0
    esc = esc_html if mode == "html" else esc_tex
    for m in TOKEN.finditer(text):
        out.append(esc(text[pos:m.start()]))
        tok = m.group(0)
        if tok == "{me}":
            out.append(f'<span class="me">{esc_html(me)}</span>' if mode == "html"
                       else "\\me{%s}" % esc_tex(me))
        elif tok == "†":
            out.append("<sup>†</sup>" if mode == "html" else "\\dg")
        elif m.group(1):                                  # [text](url)
            txt, url = m.group(1), m.group(2)
            out.append(f'<a href="{esc_html(url)}" target="_blank" rel="noopener">{esc_html(txt)}</a>'
                       if mode == "html"
                       else "\\href{%s}{%s}" % (esc_tex_url(url), esc_tex(txt)))
        elif m.group(3):                                  # _emphasis_
            out.append(f"<em>{esc_html(m.group(3))}</em>" if mode == "html"
                       else "\\textit{%s}" % esc_tex(m.group(3)))
        pos = m.end()
    out.append(esc(text[pos:]))
    return "".join(out)


# ── HTML rendering ───────────────────────────────────────────────────────────
def h_entries(items, cv):
    rows = []
    for e in items:
        detail = " · ".join(e.get("detail", []))
        rows.append(
            '      <div class="entry">\n'
            f'        <div class="when">{inline(e["when"], "html", cv["me"])}</div>\n'
            '        <div class="what">\n'
            f'          <h3>{inline(e["what"], "html", cv["me"])}</h3>\n'
            + (f'          <p>{inline(detail, "html", cv["me"])}</p>\n' if detail else "")
            + '        </div>\n      </div>'
        )
    return "\n".join(rows)


def h_figures(figs):
    out = []
    for f in figs:
        cls = ' class="fig-narrow"' if f.get("narrow") else ""
        out.append(
            f'        <figure{cls}>\n'
            f'          <img src="{esc_html(f["src"])}" alt="{esc_html(f.get("alt", ""))}">\n'
            f'          <figcaption>{inline(f.get("caption", ""), "html")}</figcaption>\n'
            f'        </figure>'
        )
    return "\n".join(out)


def h_research(cv):
    out = []
    for i, area in enumerate(cv["research"], 1):
        subs = []
        for j, s in enumerate(area["subs"]):
            bl = "\n".join(f'              <li>{inline(b, "html", cv["me"])}</li>' for b in s["bullets"])
            subs.append(
                f'          <div>\n'
                f'            <h4>{chr(96+j+1)}) {inline(s["title"], "html", cv["me"])}</h4>\n'
                f'            <ul>\n{bl}\n            </ul>\n'
                f'          </div>'
            )
        figs = h_figures(area.get("figures", []))
        out.append(
            f'      <div class="area">\n'
            f'        <h3><span class="idx">{i:02d}</span>{inline(area["title"], "html", cv["me"])}</h3>\n'
            f'        <div class="sub">\n' + "\n".join(subs) + '\n        </div>\n'
            + (figs + "\n" if figs else "")
            + f'      </div>'
        )
    return "\n".join(out)


def h_skills(cv):
    out = []
    for g in cv["skills"]:
        chips = "".join(f'<span class="chip">{esc_html(i)}</span>' for i in g["items"])
        out.append(
            f'      <div class="skill">\n'
            f'        <h3>{esc_html(g["label"])}</h3>\n'
            f'        <div class="chips">{chips}</div>\n'
            f'      </div>'
        )
    return "\n".join(out)


def cite_html(p, cv):
    bits = [inline(p["authors"], "html", cv["me"]) + ". " + inline(p["title"], "html", cv["me"]) + "."]
    if p.get("venue"):
        tail = f' <span class="venue">{esc_html(p["venue"])}</span>'
        if p.get("volume"):
            tail += f', <b>{esc_html(p["volume"])}</b>'
        if p.get("pages"):
            tail += f', {esc_html(p["pages"])}'
        if p.get("year"):
            tail += f' ({esc_html(p["year"])})'
        bits.append(tail + ".")
    st = STATUS.get(p.get("status", ""))
    if st:
        bits.append(f'<span class="{st["cls"]}">{st["label"]}</span>')
    links = []
    if p.get("doi"):
        links.append(f'<a class="lnk" href="https://doi.org/{esc_html(p["doi"])}" target="_blank" rel="noopener">DOI</a>')
    if p.get("pdf"):
        links.append(f'<a class="lnk pdf" href="{esc_html(p["pdf"])}" target="_blank" rel="noopener">PDF</a>')
    body = "".join(bits)
    if links:
        body += '\n          <div class="links">' + "".join(links) + "</div>\n        "
    return f'        <li>{body}</li>'


def h_publications(cv):
    return "\n".join(cite_html(p, cv) for p in cv["publications"])


def h_talks(cv):
    out = []
    for t in cv["talks"]:
        out.append(
            f'        <li>{inline(t["authors"], "html", cv["me"])}. “{inline(t["title"], "html", cv["me"])}.” '
            f'<span class="venue">{esc_html(t["venue"])}</span>, {esc_html(t["date"])}, {esc_html(t["location"])}.</li>'
        )
    return "\n".join(out)


def h_patents(cv):
    out = []
    for p in cv["patents"]:
        st = STATUS.get(p.get("status", ""))
        badge = f'<span class="{st["cls"]}">{st["label"]}</span>' if st else ""
        out.append(
            f'        <li>{inline(p["authors"], "html", cv["me"])}. “{inline(p["title"], "html", cv["me"])}.” '
            f'<span class="pdetail">{esc_html(p["detail"])}.</span>{badge}</li>'
        )
    return "\n".join(out)


HTML_SECTIONS = [
    ("statement",    "Statement",    "Statement",    lambda cv: f'      <p class="lede">{inline(cv["statement"], "html", cv["me"])}</p>'),
    ("education",    "Education",    "Education",    lambda cv: h_entries(cv["education"], cv)),
    ("experience",   "Experience",   "Experience",   lambda cv: h_entries(cv["experience"], cv)),
    ("research",     "Research",     "Research",     h_research),
    ("skills",       "Skills",       "Skills",       h_skills),
    ("publications", "Publications · SCIE &amp; ESCI", "Publications", h_publications),
    ("talks",        "Conferences &amp; Presentations", "Talks", h_talks),
    ("patents",      "Patents",      "Patents",      h_patents),
    ("honors",       "Honors &amp; Awards", "Honors", lambda cv: h_entries(cv["honors"], cv)),
]

LIST_SECTIONS = {"publications", "talks", "patents"}


def build_html(cv):
    tpl = open(os.path.join(ROOT, "templates", "page.html"), encoding="utf-8").read()

    photo_path = os.path.join(ROOT, cv["photo"])
    with open(photo_path, "rb") as f:
        photo = "data:image/jpeg;base64," + base64.b64encode(f.read()).decode()

    meta = []
    for k, label in [("email", "Email"), ("mobile", "Phone"), ("lab", "Lab"), ("based", "Based")]:
        v = cv["personal"].get(k)
        if not v:
            continue
        val = f'<a href="mailto:{v}">{v}</a>' if k == "email" else f"<span>{esc_html(v)}</span>"
        meta.append(f'      <li><span class="k">{label}</span>{val}</li>')

    social = []
    for l in cv["links"]:
        icon = ICONS.get(l.get("icon", "link"), ICONS["link"])
        social.append(
            f'      <li>\n'
            f'        <a href="{esc_html(l["url"])}" target="_blank" rel="noopener">\n'
            f'          <svg class="ico" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">{icon}</svg>\n'
            f'          {esc_html(l["label"])}<span class="arw">↗</span>\n'
            f'        </a>\n      </li>'
        )

    nav, secs = [], []
    for i, (sid, title, navlabel, fn) in enumerate(HTML_SECTIONS, 1):
        nav.append(f'        <li><a href="#{sid}"><span class="n">{i:02d}</span>{navlabel}</a></li>')
        body = fn(cv)
        if sid in LIST_SECTIONS:
            body = f'      <ol class="list">\n{body}\n      </ol>'
            if sid == "publications" and cv.get("publications_note"):
                body += f'\n      <p class="note">{esc_html(cv["publications_note"])}</p>'
        secs.append(f'    <section id="{sid}">\n      <h2>{title}</h2>\n{body}\n    </section>')

    parts = cv["me"].split()
    out = (BANNER_HTML + tpl
           .replace("{{PHOTO}}", photo)
           .replace("{{NAME_BR}}", "<br>".join([parts[0], " ".join(parts[1:])]) if len(parts) > 1 else cv["me"])
           .replace("{{NAME}}", esc_html(cv["me"]))
           .replace("{{ROLE}}", "<br>".join(esc_html(r) for r in cv["role_lines"]))
           .replace("{{META}}", "\n".join(meta))
           .replace("{{SOCIAL}}", "\n".join(social))
           .replace("{{NAV}}", "\n".join(nav))
           .replace("{{SECTIONS}}", "\n\n".join(secs))
           .replace("{{EMAIL}}", cv["personal"]["email"])
           .replace("{{UPDATED}}", esc_html(cv["updated"])))
    return out


# ── LaTeX rendering ──────────────────────────────────────────────────────────
def t_entries(items, cv):
    out = []
    for e in items:
        what = inline(e["what"], "tex", cv["me"])
        detail = [inline(d, "tex", cv["me"]) for d in e.get("detail", [])]
        if e.get("inline_detail") and detail:
            # 원본 Word CV 스타일: "제목 (부연 설명)" 한 줄로
            body = "%s (%s)" % (what, ", ".join(detail))
        else:
            body = "\\\\\n  ".join([what] + detail)
        out.append("\\entry{%s}{%s}" % (inline(e["when"], "tex", cv["me"]), body))
    return "\n".join(out)


def t_figures(figs, cv):
    out = []
    for f in figs:
        if not f.get("in_pdf"):
            continue
        out.append(
            "\\begin{center}\n"
            "  \\includegraphics[width=0.8\\textwidth]{%s}\n" % f["src"] +
            "  \\par\\vspace{3pt}{\\small %s}\n" % inline(f.get("caption", ""), "tex", cv["me"]) +
            "\\end{center}"
        )
    return "\n".join(out)


def t_research(cv):
    out = []
    for i, area in enumerate(cv["research"], 1):
        out.append("\\textbf{%d. %s}\\par\n\\vspace{3pt}" % (i, inline(area["title"], "tex", cv["me"])))
        for j, s in enumerate(area["subs"]):
            out.append("\\hspace{1.2em}%s) %s" % (chr(97 + j), inline(s["title"], "tex", cv["me"])))
            out.append("\\begin{itemize}")
            out += ["  \\item %s" % inline(b, "tex", cv["me"]) for b in s["bullets"]]
            out.append("\\end{itemize}")
            if j < len(area["subs"]) - 1:
                out.append("\\vspace{4pt}")
        figs = t_figures(area.get("figures", []), cv)
        if figs:
            out.append(figs)
        if i < len(cv["research"]):
            out.append("\n\\vspace{7pt}")
    return "\n".join(out)


def t_skills(cv):
    out = []
    for k, g in enumerate(cv["skills"]):
        out.append("\\textbf{%s}" % esc_tex(g["label"]))
        out.append("\\begin{itemize}")
        out.append("  \\item %s" % ", ".join(esc_tex(i) for i in g["items"]))
        out.append("\\end{itemize}")
        if k < len(cv["skills"]) - 1:
            out.append("\\vspace{4pt}")
    return "\n".join(out)


def cite_tex(p, cv):
    s = inline(p["authors"], "tex", cv["me"]) + ", " + inline(p["title"], "tex", cv["me"])
    if p.get("venue"):
        s += ", \\venue{%s}" % esc_tex(p["venue"])
        if p.get("volume"):
            s += ", \\textbf{%s}" % esc_tex(p["volume"])
        if p.get("pages"):
            s += ", %s" % esc_tex(p["pages"])
    st = STATUS.get(p.get("status", ""))
    tail = []
    if st and st["tex"]:
        tail.append(st["tex"])
    if p.get("year"):
        tail.append("(%s)" % esc_tex(p["year"]))
    if tail:
        s += ", " + ", ".join(tail)
    s += "."
    if p.get("doi"):
        s += " \\href{https://doi.org/%s}{doi:%s}" % (esc_tex_url(p["doi"]), esc_tex(p["doi"]))
    return "  \\item " + s


def t_publications(cv):
    body = "\n\n".join(cite_tex(p, cv) for p in cv["publications"])
    s = "\\begin{enumerate}\n%s\n\\end{enumerate}" % body
    if cv.get("publications_note"):
        s += "\n\\vspace{3pt}\n(%s)" % esc_tex(cv["publications_note"])
    return s


def t_talks(cv):
    items = []
    for t in cv["talks"]:
        items.append("  \\item %s, ``%s'', %s, %s, %s" % (
            inline(t["authors"], "tex", cv["me"]), inline(t["title"], "tex", cv["me"]),
            esc_tex(t["venue"]), esc_tex(t["date"]), esc_tex(t["location"])))
    return "\\begin{enumerate}\n%s\n\\end{enumerate}" % "\n\n".join(items)


def t_patents(cv):
    items = []
    for p in cv["patents"]:
        items.append("  \\item %s, ``%s'', (%s)." % (
            inline(p["authors"], "tex", cv["me"]), inline(p["title"], "tex", cv["me"]),
            esc_tex(p["detail"])))
    return "\\begin{enumerate}\n%s\n\\end{enumerate}" % "\n\n".join(items)


TEX_SECTIONS = [
    ("Personal Statement",           lambda cv: inline(cv["statement"], "tex", cv["me"])),
    ("Academic Education",           lambda cv: t_entries(cv["education"], cv)),
    ("Work Experiences",             lambda cv: t_entries(cv["experience"], cv)),
    ("Honors and Awards",            lambda cv: t_entries(cv["honors"], cv)),
    ("Research Area",                t_research),
    ("Research skills and experiences", t_skills),
    ("Publications (SCIE \\& ESCI)", t_publications),
    ("Conferences and Presentations", t_talks),
    ("Patents",                      t_patents),
]


def build_tex(cv):
    tpl = open(os.path.join(ROOT, "templates", "doc.tex"), encoding="utf-8").read()

    fields = []
    for label, key in [("Name", None), ("Mobile", "mobile"), ("Email", "email"),
                       ("Date of Birth", "dob"), ("Address", "address")]:
        if key is None:
            fields.append("  \\field{Name}{%s}" % esc_tex(cv["me"]))
        elif cv["personal"].get(key):
            v = cv["personal"][key]
            if key == "email":
                v = "\\href{mailto:%s}{%s}" % (v, esc_tex(v))
            else:
                v = esc_tex(v)
            fields.append("  \\field{%s}{%s}" % (label, v))
    if cv.get("links"):
        joined = "\n        \\;\\textperiodcentered\\;\n        ".join(
            "\\href{%s}{%s}" % (esc_tex_url(l["url"]), esc_tex(l.get("tex_label", l["label"])))
            for l in cv["links"])
        fields.append("  \\field{Links}{%s}" % joined)

    secs = []
    for title, fn in TEX_SECTIONS:
        secs.append("\\cvsection{%s}\n%s" % (title, fn(cv)))

    return (BANNER_TEX + tpl
            .replace("{{FIELDS}}", "\n".join(fields))
            .replace("{{PHOTO}}", cv["photo"])
            .replace("{{SECTIONS}}", "\n\n".join(secs)))


# ── main ─────────────────────────────────────────────────────────────────────
def main():
    with open(os.path.join(ROOT, "cv.json"), encoding="utf-8") as f:
        cv = json.load(f)

    html = build_html(cv)
    with open(os.path.join(ROOT, "index.html"), "w", encoding="utf-8") as f:
        f.write(html)
    print("  index.html  %6d bytes" % len(html))

    tex = build_tex(cv)
    with open(os.path.join(ROOT, "cv.tex"), "w", encoding="utf-8") as f:
        f.write(tex)
    print("  cv.tex      %6d bytes" % len(tex))

    print("  %d publications · %d patents · %d talks"
          % (len(cv["publications"]), len(cv["patents"]), len(cv["talks"])))

    if "--pdf" in sys.argv:
        for _ in range(2):
            r = subprocess.run(["pdflatex", "-interaction=nonstopmode", "cv.tex"],
                               cwd=ROOT, capture_output=True)
        if os.path.exists(os.path.join(ROOT, "cv.pdf")):
            print("  cv.pdf      %6d bytes" % os.path.getsize(os.path.join(ROOT, "cv.pdf")))
        else:
            print("  ! pdflatex failed — see cv.log")
            sys.exit(1)


if __name__ == "__main__":
    main()
